In [ ]:
#LOADING NUMPY
import numpy as np            #not a built-in library, need to be installed

THE BASICS

In [27]:
#basic syntax
a = np.array([1,34,97850])
b = np.array([[1,2,3],[56,78,89]])
#In Jupyter notebook, we don't really need to write the print command to get the output as opposed to traditional Python syntax
print(a)
print(b)      #but a print statement is used for getting more than one line of o/p

[    1    34 97850]
[[ 1  2  3]
 [56 78 89]]


In [28]:
#understanding the dimensions of array, can be 2/3/so on....

print(a.ndim)       #a 1-D array with 1 row and 3 columns
print(b.ndim)       #a 2-D array pr a '2x2' matrix with 2 rows and 3 columns 


1
2


In [ ]:
#Understanding the shape of an array
print(a.shape)     
print(b.shape)                      

(3,)
(2, 3)


In [11]:
#Getting the type
print(a.dtype)
print(b.dtype)

int64
int64


In [ ]:
#Getting the itemsize
print(a.itemsize)         #since it's an item of 'type' integer of 64-bits i.e. an integer of 'size' '8'-bytes (8 bits = 1 byte)
print(b.itemsize)

8
8


In [ ]:
#Getting the size - i.e. the total number of elements present in the array
print(a.size)                
print(b.size)

3
6


In [ ]:
#Getting the total size = no. of elements x size of the array(in bytes)
a.size * a.itemsize
#or
print(a.nbytes)           #3*8
print(b.nbytes)           #6*8


24
48


ACCESSING/CHANGING specific elements/rows/columns

In [31]:
mat = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
print(mat)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [ ]:
#To get a specific element
#Indexing starts with '0'
#notation - array[row,column]

print(mat[0,0])    #i.e. the first element of the first row and column
print(mat[0,3])    #first row element
print(mat[1,4])    #second row element
print(mat[2,5])    #third/last row, fifth'last column element
print(mat[-1,-1])  #another way to get the last element

1
4
11
18
18


In [ ]:
#To get elements of a specific row/or a specific row - array[row, :]  ':' represents 'all'
mat[1,:]       

array([ 7,  8,  9, 10, 11, 12])

In [ ]:
#To get elements of a specific column/or a specific column
mat[:,2]

array([ 3,  9, 15])

In [62]:
#Let's get a lil fancier - [startindex:endindex:stepsize] 'stepsize' i.e. how many steps to take 

#when array[row, column = startindex:endindex:stepsize]
print(mat[0, 0:4:1])
print(mat[-1, 1:6:2])

#when array[row = startindex:endindex:stepsize, column]
print(mat[0:3:1, 4])
print(mat[-1:3:1, 2])

[1 2 3 4]
[14 16 18]
[ 5 11 17]
[15]


3-DIMENSIONAL ARRAYS - can be understood as 2-D Arrays stacked together

In [21]:
threeDimArr = np.array([[[1,2], [3,4]],[[5,6],[7,8]]])
print(threeDimArr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
#Getting specific element (work outside in - first find which layer, then which row/column of the layer, then the pos ind of the ele)
# For Ex - I wanna get ele '4' - which is in '1st'('0' ind) layer, '2nd'('1' ind) row and '2nd'('1' ind) ele of the row
print(threeDimArr[0,1,1])


4


In [24]:
#Replacing elements 
threeDimArr[:,1,:] = [[23,68639], [3658, 0]]
print(threeDimArr)

[[[    1     2]
  [   23 68639]]

 [[    5     6]
  [ 3658     0]]]


TYPES OF ARRAYS/MATRIX that can be represented through some built-in function in NumPy

In [ ]:
#Zero Matrix
np.zeros((3,3,3))          #a '3' layered, '3x3' row-column '0x0' matrix

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
#All-ones Matrix
np.ones((3,3,3))     #a '3' layered, '3x3' row-column '1x1' matrix

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [53]:
#Constant Matrix - all entries being equal
#Given by - np.full((layerxixj),(val))
ex = np.full((2,2,2),31, dtype='float64')       #a 2D '2x2' matrix, all entries being equal/const i.e. 31, can define the type
print(ex)

#full_like method - to create a matrix similar to another matrix created before - let's create ano mat sim to ex
eg = np.full_like(ex, 7)
print(eg)

[[[31. 31.]
  [31. 31.]]

 [[31. 31.]
  [31. 31.]]]
[[[7. 7.]
  [7. 7.]]

 [[7. 7.]
  [7. 7.]]]


In [ ]:
#Identity Matrix